name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Restore Next.js cache
        uses: actions/cache@v3
        with:
          path: .next
          key: nextjs-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nextjs-${{ github.ref }}-
            nextjs-

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Debug file structure
        run: ls -R src/components

      - name: Build
        run: npm run build

      - name: Run Linters
        run: npm run lint
